### ISSUE TITLE
Getting an error trying to send any command to the AP - Template Error

### ISSUE THREAD

**Issue by WillowMist** [cardinal-dev/Cardinal#168]
I've hit several hurdles trying to get cardinal installed, and I've finally stumped myself on this.  I think I finally have the environment variables set properly, and have scout finding the right config variables.  But now I get this:

`[2022-05-21 01:41:39,651] ERROR in app: Exception on /get-ap-info [POST]
Traceback (most recent call last):
  File "/home/jason/Cardinal/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jason/Cardinal/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jason/Cardinal/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jason/Cardinal/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/jason/Cardinal/webapp/./cardinal/views/cardinal_ap_ops.py", line 150, in fetchApInfo
    status = gatherApInfo(apId)
  File "/home/jason/Cardinal/webapp/./cardinal/system/cardinal_fetch.py", line 57, in gatherApInfo
    apInfo = info.fetcher(ip=apIp, username=apSshUsername, password=apSshPassword)
  File "/home/jason/Cardinal/lib/python3.8/site-packages/scout/info.py", line 198, in fetcher
    cmdTemplate = jinjaEnv.get_template("scout_fetcher")
  File "/home/jason/Cardinal/lib/python3.8/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/home/jason/Cardinal/lib/python3.8/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/jason/Cardinal/lib/python3.8/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/jason/Cardinal/lib/python3.8/site-packages/jinja2/loaders.py", line 214, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: scout_fetcher
[pid: 3253|app: 0|req: 19/45] 192.168.0.248 () {52 vars in 1173 bytes} [Sat May 21 01:41:39 2022] POST /get-ap-info => generated 290 bytes in 613 msecs (HTTP/1.1 500) 3 headers in 113 bytes (1 switches on core 0)
`

I'm guessing that a path isn't set correctly, and jinja2 isn't seeing the template directory in scout for whatever reason.  But I'm not sure where I should start  looking.

Any suggestions?

Thanks

**Comment by falcon78921** [comment]
Hey @WillowMist :wave: 

Could you please provide a redacted version of the `cardinal.ini` file being used?

**Comment by WillowMist** [comment]
[cardinal.ini.txt](https://github.com/cardinal-dev/Cardinal/files/8750028/cardinal.ini.txt)

**Comment by falcon78921** [comment]
Thanks for the info @WillowMist. I'm in the process of changing the `.ini` values to `camelCase`, but the Cardinal upstream hasn't implemented that yet. Could you please try adapting your `cardinal.ini` to look like the following?

```
[cardinal]
dbserver=mariadb
dbuser=root
dbpassword=test1234
dbname=cardinal
flaskkey=d67ff999decd7439c230f519ea9fb999
encryptkey=W-kYJoioEnIscpjhwraQlE54XkqxeNUByt-3A-az_xU=
workers=2
sessionTimeout=10000
```
`camelCase` is being enforced on the Scout side, so `commandDir` looks good. Does `/home/jason/Cardinal/lib/python3.8/site-packages/scout` have the templates sitting out or are they in another directory inside `/home/jason/Cardinal/lib/python3.8/site-packages/scout`? By default, `scout` is packaged with `templates/` inside the root:

```
scout/scout$ tree templates/
templates/
├── scout_change_ap_ip
├── scout_change_ap_name
├── scout_create_radius_ssid_24
├── scout_create_radius_ssid_5
├── scout_create_ssid_24
├── scout_create_ssid_5
├── scout_delete_ssid_24
├── scout_delete_ssid_5
├── scout_disable_ap_http
├── scout_disable_ap_snmp
├── scout_do_tftp_backup
├── scout_do_wr
├── scout_enable_ap_http
├── scout_enable_ap_snmp
├── scout_fetcher
├── scout_get_hostname
├── scout_get_location
├── scout_get_users
├── scout_reboot_ap
├── scout_ssh_ping
└── scout_write_default
```

**Comment by WillowMist** [comment]
They're in the root of the scout package, under template, as above.

**Comment by falcon78921** [comment]
@WillowMist If you set `commandDir=/home/jason/Cardinal/lib/python3.8/site-packages/scout/templates`, does the `Fetch AP Info` function work?

**Comment by WillowMist** [comment]
`
[2022-05-23 23:21:14,069] ERROR in app: Exception on /get-ap-info [POST]
Traceback (most recent call last):
  File "/home/jason/Cardinal/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jason/Cardinal/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jason/Cardinal/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jason/Cardinal/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/jason/Cardinal/webapp/./cardinal/views/cardinal_ap_ops.py", line 150, in fetchApInfo
    status = gatherApInfo(apId)
  File "/home/jason/Cardinal/webapp/./cardinal/system/cardinal_fetch.py", line 57, in gatherApInfo
    apInfo = info.fetcher(ip=apIp, username=apSshUsername, password=apSshPassword)
  File "/home/jason/Cardinal/lib/python3.8/site-packages/scout/info.py", line 219, in fetcher
    apBandwidth = apBandwidthRegex.search(sshData[3]).group(0)
AttributeError: 'NoneType' object has no attribute 'group'

`

I'm assuming it's not hitting fetch properly.  I'm going to try to copy the templates to the scout folder.

**Comment by WillowMist** [comment]
Nope, even with the templates in the scout folder, and changing the commandDir back, I'm getting the above sshData attribute error

**Comment by falcon78921** [comment]
Thanks for the info @WillowMist. It looks like Scout is able to find the templates now, so that's progress :+1:

Out of curiosity, which Cisco AP model are you attempting to fetch info from?

**Comment by WillowMist** [comment]
C1042 -- The SSH does appear to be working ok.

**Comment by WillowMist** [comment]
The 1042 uses C1140 firmware, by the way

**Comment by WillowMist** [comment]
I just verified that the scout library works.  I was able to run the ping, getMac, getSpeed, etc methods in the venv.

**Comment by WillowMist** [comment]
However, fetcher DOES fail, with the same error.  I'll dig further.

**Comment by falcon78921** [comment]
Thanks @WillowMist, that's good info :+1: 

Just curious, if you drop a debugger (e.g. `remote-pdb`) after line 219 (https://github.com/cardinal-dev/scout/blob/main/scout/info.py#L219), connect to the debug session, and then `print(sshData[])`, what does that look like?

`remote-pdb` is a good tool to use. You can add the following after line 219:

```
from remote_pdb import RemotePdb
RemotePdb("127.0.0.1", 4444).set_trace()
```

Here's a quick step-by-step (you can do this inside or outside Cardinal):
```
git clone https://github.com/cardinal-dev/scout.git
cd scout
python3 -m venv venv
source venv/bin/activate
pip install -U pip
pip install remote-pdb
export SCOUTCONFIG=/tmp/scout/conf/scout.ini (be sure to point to templates/ directory)
cd scout/ (inside package)
python3
import info
info.fetcher("<AP_IP>", "<USER>", "<PASS>")
```
If `info.fetcher()` hangs, open another Terminal and then connect to the `remote_pdb` session via Telnet:

```
telnet 127.0.0.1 4444
```
If you can copy/paste the redacted output of `sshData` here, that would definitely help debug what's happening.

**Comment by WillowMist** [comment]
Well, I think I've found the issue.  show interface gi0 | i Mbps returns nothing, so it's choking in that spot.  Looks like the speed line returns Mb/s as a string rather than Mbps.

**Comment by falcon78921** [comment]
@WillowMist Interesting, could you please copy/paste the output of `show interface gi0 | i Mbps` against your Cisco AP?

**Comment by WillowMist** [comment]
Literally nothing.   Here's the whole of interface gi0:

`
GigabitEthernet0 is up, line protocol is up 
  Hardware is PowerPC405ex Ethernet, address is d867.d99f.891b (bia d867.d99f.891b)
  MTU 1500 bytes, BW 1000000 Kbit/sec, DLY 10 usec, 
     reliability 255/255, txload 1/255, rxload 1/255
  Encapsulation ARPA, loopback not set
  Full-duplex, 1000Mb/s, media type is T
  output flow-control is unsupported, input flow-control is unsupported
  ARP type: ARPA, ARP Timeout 04:00:00
  Last input 00:00:00, output 00:00:00, output hang never
  Last clearing of "show interface" counters never
  Input queue: 0/1677/0/0 (size/max/drops/flushes); Total output drops: 0
  Queueing strategy: fifo
  Output queue: 0/40 (size/max)
  5 minute input rate 13000 bits/sec, 11 packets/sec
  5 minute output rate 0 bits/sec, 0 packets/sec
     2464586 packets input, 364592312 bytes, 0 no buffer
     Received 2432514 broadcasts, 0 runts, 0 giants, 0 throttles
     0 input errors, 0 CRC, 0 frame, 0 overrun, 0 ignored
     0 watchdog, 0 multicast, 0 pause input
     0 input packets with dribble condition detected
     25439 packets output, 9945263 bytes, 0 underruns
     0 output errors, 0 collisions, 2 interface resets
     20 unknown protocol drops
     0 babbles, 0 late collision, 0 deferred
     0 lost carrier, 0 no carrier, 0 pause output
     0 output buffer failures, 0 output buffers swapped out
`

**Comment by WillowMist** [comment]
It may be because I had to go to a really old firmware for the AP to change it over to autonomous mode.   Possibly just a change in return format from the AP?

**Comment by WillowMist** [comment]
`one#show interface gi0 | i Mb/s

  Full-duplex, 1000Mb/s, media type is T

one#
`

**Comment by falcon78921** [comment]
Thanks @WillowMist

> It may be because I had to go to a really old firmware for the AP to change it over to autonomous mode. Possibly just a change in return format from the AP?

Yep, good catch :+1: I currently do CI/CD testing with a Cisco 1142N and 3602i only. Honestly, I've only seen the `Mb/s` format on switches/routers, never APs. I learn something new everyday :smile:

It would be awesome to accommodate as many models as possible, but I also admit that could be a bit challenging, especially with the small IOS changes Cisco implements. From a template perspective, this would be a very simple fix and should accommodate your device. However, I'm not sure if changing the template to `Mb/s` upstream would be ideal. This is good info and I'll definitely have to think about.

Just to confirm, if you change from `Mbps` to `Mb/s`, does the fetch complete successfully?

**Comment by WillowMist** [comment]
Yea, I was just looking at that line :)  I'll let you know ASAP.

**Comment by WillowMist** [comment]
```
2022-05-24 00:52:55.420741 INFO: Gathered access point information for one in: 8.144917488098145
```

**Comment by WillowMist** [comment]
Well, I've got 65 of these APs.  So I can run a customized version of scout, if I need to :)  If you'd like, I'll work up a check to accommodate the Mb/s output.  And if I spot any other differences, I'll submit them as a PR for scout or cardinal.

**Comment by falcon78921** [comment]
That would be awesome @WillowMist :+1: 

I'll continue to brainstorm and see if I can come up with a good, sustainable way of accounting for different IOS formats.

Thanks for using Cardinal! :)

**Comment by WillowMist** [comment]
By the way, I love the idea of this project.  I'm a huge fan or repurposing hardware that's being retired.  An open source controller can give APs extended life. :)

**Comment by chrispro-21** [comment]
> Thanks @WillowMist
> 
> > It may be because I had to go to a really old firmware for the AP to change it over to autonomous mode. Possibly just a change in return format from the AP?
> 
> Yep, good catch 👍 I currently do CI/CD testing with a Cisco 1142N and 3602i only. Honestly, I've only seen the `Mb/s` format on switches/routers, never APs. I learn something new everyday 😄
> 
> It would be awesome to accommodate as many models as possible, but I also admit that could be a bit challenging, especially with the small IOS changes Cisco implements. From a template perspective, this would be a very simple fix and should accommodate your device. However, I'm not sure if changing the template to `Mb/s` upstream would be ideal. This is good info and I'll definitely have to think about.
> 
> Just to confirm, if you change from `Mbps` to `Mb/s`, does the fetch complete successfully?
> 
> EDIT: Actually, just remembered, you'll probably have to change the regex definition in `info.py` as well: https://github.com/cardinal-dev/scout/blob/main/scout/info.py#L215.

I have a few of the 2702i's and they sho in Gbps
`ap_2#sho interface gi0 | i Gbps
  Full Duplex, 1Gbps, media type is T
ap_2#`
