### ISSUE TITLE
[Bug] Internal Server Error when enabling HTTP on Access Point

### ISSUE THREAD

**Issue by chrispro-21** [cardinal-dev/Cardinal#196]
Disabling HTTP works fine, but I get a tuple out-of-range error when trying to enable it. PR incoming.

Here is the logs:
```
ui_1       | 10.20.0.216 - - [19/Dec/2022:17:28:12 +0000] "GET /config-ap-http?status=HTTP+Server+for+MY-ACCESS-POINT+Successfully+Disabled HTTP/1.1" 200 360 "http://[MY_DOMAIN_HERE]:1000/config-ap-http" "Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0"
ui_1       | [2022-12-19 17:28:16,686] ERROR in app: Exception on /enable-ap-http [POST]
ui_1       | Traceback (most recent call last):
ui_1       |   File "/opt/venv/cardinal/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
ui_1       |     response = self.full_dispatch_request()
ui_1       |   File "/opt/venv/cardinal/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
ui_1       |     rv = self.handle_user_exception(e)
ui_1       |   File "/opt/venv/cardinal/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
ui_1       |     rv = self.dispatch_request()
ui_1       |   File "/opt/venv/cardinal/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
ui_1       |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
ui_1       |   File "/opt/Cardinal/webapp/./cardinal/views/cardinal_ap_ops.py", line 170, in enableApHttp
ui_1       |     encryptedSshPassword = bytes(apInfo[3], 'utf-8')
ui_1       | IndexError: tuple index out of range
```

**Comment by falcon78921** [comment]
Reproduced with latest source:

```
ui_1       | [2022-12-23 18:34:01,086] ERROR in app: Exception on /enable-ap-http [POST]
ui_1       | Traceback (most recent call last):
ui_1       |   File "/opt/venv/cardinal/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
ui_1       |     response = self.full_dispatch_request()
ui_1       |   File "/opt/venv/cardinal/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
ui_1       |     rv = self.handle_user_exception(e)
ui_1       |   File "/opt/venv/cardinal/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
ui_1       |     rv = self.dispatch_request()
ui_1       |   File "/opt/venv/cardinal/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
ui_1       |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
ui_1       |   File "/opt/Cardinal/webapp/./cardinal/views/cardinal_ap_ops.py", line 170, in enableApHttp
ui_1       | IndexError: tuple index out of range
ui_1       | [pid: 32|app: 0|req: 49/107] 172.19.0.1 () {66 vars in 1598 bytes} [Fri Dec 23 18:34:01 2022] POST /enable-ap-http => generated 290 bytes in 5 msecs (HTTP/1.1 500) 3 headers in 113 bytes (2 switches on core 0)
```
